ARG centos=7.8.2003
FROM aursu/rpmbuild:${centos}-build

USER root
RUN yum -y install \
         bzip2-devel \
         cmake3 \
         openssl-devel \
         xz-devel \
         zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
